import type { Metadata } from "next";
import StoreProvider from "./StoreProvider";
import "./globals.css";


export const metadata: Metadata = {
  title: "PixAI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className="min-h-screen bg-background text-foreground antialiased transition-colors duration-300"
      >
        <StoreProvider>
        {children}
        </StoreProvider>
      </body>
    </html>
  );
}
